/**
 * Tracking of mutating-request event ids generated by THIS tab.
 *
 * Every non-GET API request gets a fresh `x-client-event-id` which the backend
 * echoes on its realtime broadcast. A tab ignores broadcasts carrying an id it
 * generated itself (its optimistic update already applied that state), while
 * other tabs — including other windows of the same user — apply them normally.
 */
const sent = new Set<string>();

export function registerClientEventId(): string {
  const id = crypto.randomUUID();
  sent.add(id);
  // Bounded FIFO prune — ids only need to survive until the echo arrives.
  if (sent.size > 256) {
    const oldest = sent.values().next().value;
    if (oldest !== undefined) sent.delete(oldest);
  }
  return id;
}

export function isOwnClientEvent(id: string | undefined | null): boolean {
  return id !== undefined && id !== null && sent.has(id);
}
