import type { Server as HttpServer } from 'node:http';
import { Server as IOServer, type Socket } from 'socket.io';
import type { Request } from 'express';
import { env } from '../config/env.js';
import { verifyToken } from '../utils/tokens.js';
import { prisma } from '../lib/prisma.js';
import { ApiError } from '../lib/errors.js';
import { loadBoardAccess, loadTeamAccess } from '../middleware/permissions.js';

/**
 * Envelope attached to every realtime broadcast.
 *
 * `clientEventId` is generated by the originating browser tab for each mutating
 * HTTP request (header `x-client-event-id`) and echoed back on the broadcast so
 * that the tab which caused the change can ignore its own echo (its optimistic
 * update already applied the same state). Other tabs/windows apply it normally.
 */
export interface RealtimeEnvelope {
  actorId: string;
  clientEventId?: string;
}

export const boardRoom = (boardId: string) => `board:${boardId}`;
export const teamRoom = (teamId: string) => `team:${teamId}`;
export const userRoom = (userId: string) => `user:${userId}`;

let io: IOServer | null = null;

/** Extract the client event id from a mutating REST request, if well-formed. */
export function clientEventId(req: Request): string | undefined {
  const raw = req.headers['x-client-event-id'];
  if (typeof raw === 'string' && raw.length > 0 && raw.length <= 64) return raw;
  return undefined;
}

function parseCookies(header: string | undefined): Record<string, string> {
  const out: Record<string, string> = {};
  if (!header) return out;
  for (const part of header.split(';')) {
    const eq = part.indexOf('=');
    if (eq === -1) continue;
    const key = part.slice(0, eq).trim();
    const value = part.slice(eq + 1).trim();
    if (key) out[key] = decodeURIComponent(value);
  }
  return out;
}

/** Called once from index.ts with the HTTP server (no-op wiring in REST tests). */
export function initSocket(server: HttpServer): IOServer {
  io = new IOServer(server, {
    cors: { origin: env.clientOrigin, credentials: true },
  });

  // Handshake auth: same JWT cookie as the REST API.
  io.use(async (socket, next) => {
    try {
      const token = parseCookies(socket.handshake.headers.cookie)[env.cookieName];
      if (!token) throw new Error('missing token');
      const { sub: userId } = verifyToken(token);
      const user = await prisma.user.findUnique({ where: { id: userId }, select: { id: true } });
      if (!user) throw new Error('user gone');
      socket.data.userId = user.id;
      next();
    } catch {
      next(new Error('unauthorized'));
    }
  });

  io.on('connection', (socket: Socket) => {
    const userId = socket.data.userId as string;

    // Personal room: every socket of this user receives their notifications,
    // no matter which board/team they are currently viewing.
    void socket.join(userRoom(userId));

    socket.on('board:join', async (boardId: unknown, ack?: (res: { ok: boolean; error?: string }) => void) => {
      if (typeof boardId !== 'string' || !boardId) {
        ack?.({ ok: false, error: 'Invalid board id' });
        return;
      }
      try {
        await loadBoardAccess(userId, boardId, 'MEMBER');
        void socket.join(boardRoom(boardId));
        ack?.({ ok: true });
      } catch (err) {
        // 404 for non-members — never leak board existence.
        ack?.({ ok: false, error: err instanceof ApiError ? err.message : 'Failed to join board' });
      }
    });

    socket.on('board:leave', (boardId: unknown) => {
      if (typeof boardId === 'string' && boardId) void socket.leave(boardRoom(boardId));
    });

    socket.on('team:join', async (teamId: unknown, ack?: (res: { ok: boolean; error?: string }) => void) => {
      if (typeof teamId !== 'string' || !teamId) {
        ack?.({ ok: false, error: 'Invalid team id' });
        return;
      }
      try {
        await loadTeamAccess(userId, teamId, 'MEMBER');
        void socket.join(teamRoom(teamId));
        ack?.({ ok: true });
      } catch (err) {
        ack?.({ ok: false, error: err instanceof ApiError ? err.message : 'Failed to join team' });
      }
    });

    socket.on('team:leave', (teamId: unknown) => {
      if (typeof teamId === 'string' && teamId) void socket.leave(teamRoom(teamId));
    });
  });

  return io;
}

export function closeSocket(): void {
  io?.close();
  io = null;
}

/** Broadcast to every socket currently viewing the board (REST routes call this). */
export function emitBoardEvent(
  boardId: string,
  type: string,
  envelope: RealtimeEnvelope,
  data: Record<string, unknown>
): void {
  io?.to(boardRoom(boardId)).emit(type, { ...envelope, ...data });
}

/** Broadcast to every socket of a team (board-level list/tab changes). */
export function emitTeamEvent(
  teamId: string,
  type: string,
  envelope: RealtimeEnvelope,
  data: Record<string, unknown>
): void {
  io?.to(teamRoom(teamId)).emit(type, { ...envelope, ...data });
}

/** Broadcast to every socket of a single user (personal notifications). */
export function emitUserEvent(
  userId: string,
  type: string,
  envelope: RealtimeEnvelope,
  data: Record<string, unknown>
): void {
  io?.to(userRoom(userId)).emit(type, { ...envelope, ...data });
}
